### ISSUE TITLE
there is not  criterion_pair2 in main.py

### ISSUE THREAD

**Issue by xiaopanchen** [BoomShakaY/AIM-CCReID#10]
train_aim(config, epoch, model, model2, classifier, clothes_classifier, clothes_classifier2, fuse, criterion_cla, criterion_pair,
            criterion_clothes, criterion_adv, criterion_pair2, optimizer, optimizer2, optimizer_cc, trainloader, pid2clothes, kl)

**Comment by BoomShakaY** [comment]
Some parts are not used in the code, I'll correct them, thanks.
