### ISSUE TITLE
can not find ClothesBasedAdversarialLossWithMemoryBank in the losses.clothes_based_adversarial_loss 

### ISSUE THREAD

**Issue by xiaopanchen** [BoomShakaY/AIM-CCReID#11]
from losses.clothes_based_adversarial_loss import ClothesBasedAdversarialLoss, ClothesBasedAdversarialLossWithMemoryBank

**Comment by liudongcan666** [comment]
是的，哥，我看论文看了一天，装环境装了一天，最后找bug找了一个下午发现ClothesBasedAdversarialLossWithMemoryBank没有，哥你可以好好发代码麻

**Comment by BoomShakaY** [comment]
ClothesBasedAdversarialLossWithMemoryBank is from the baseline and is not used in the code, I'll correct them, thanks.

**Comment by BoomShakaY** [comment]
@zhouxingxing1024 The environment used is not complicated, and I thought you might have problems related to the apex. You can comment all the amp related codes if you have enough GPU memory, and including amp for training might lower the performance.
