### ISSUE TITLE
mAP and top1 is bad on some datasets 

### ISSUE THREAD

**Issue by QiqLiang** [BoomShakaY/AIM-CCReID#13]
Hi, I tried to validate the market1501 dataset and last dataset using your lrcc model and prcc model, but got extremely low map and top1 accuracy: 
Model      Market1501                             LaST 
PRCC       Top1=21.2 map=7.9                Top1=17.2 map=2.6
LRCC       Top1=40.7 map=19.7              Top1=24.6 map=4.2
But the validation on prcc dataset is just normal, just as what is said in the readme.
Why does it happen? Is it because it is not suitable for cross domain?

**Comment by BoomShakaY** [comment]
The cross-domain might be a problem, so you can take a look at the domain generalization methods for help.
