### ISSUE TITLE
how to make this graph?

### ISSUE THREAD

**Issue by 1024AILab** [BoomShakaY/AIM-CCReID#6]
![image](https://github.com/BoomShakaY/AIM-CCReID/assets/39455680/c3512777-8daa-42af-b0af-72597374b919)
Hi author how to make this graph?

**Comment by BoomShakaY** [comment]
Hi, you can make this graph by t-SNE after obtaining the identity feature for any dataset. 
This figure only shows 10 randomly selected classes, with 50 randomly selected samples in each class.
