### ISSUE TITLE
所给的预训练模型prcc.pth.tar中 的checkpoint的键名只有model_state_dict

### ISSUE THREAD

**Issue by miaomiaogg** [BoomShakaY/AIM-CCReID#7]
你好，作者，请问你所给的预训练模型prcc.pth.tar中 的checkpoint的键名只有model_state_dict这一个内容，我并没有看到classifier_state_dict，fuse_state_dict，model2_state_dict，clothes_classifier_state_dict，clothes_classifier2_state_dict，epoch这些东西，是当时保存模型的时候没有保存进去吗？

**Comment by BoomShakaY** [comment]
是的，提供的pth仅包含测试部分所需要的参数，其他的参数未保存。
