### ISSUE TITLE
训出的模型达不到所发布的模型参数效果

### ISSUE THREAD

**Issue by Acedess** [BoomShakaY/AIM-CCReID#8]
作者您好，我发现在默认配置文件中缺少一些loss相关参数：
_C.LOSS.PAIR_LOSS
_C.LOSS.PAIR_M
_C.LOSS.PAIR_S
_C.LOSS.PAIR_LOSS_WEIGHT
于是在训练过程中，我将这些缺失的配置参数设置为相应loss函数中的默认值，最后训出的模型在PRCC上差距6%左右，在LTCC上差距2%左右，想请教一下可能是哪方面的原因呢？（k_cal和k_kl已按论文中设置）

**Comment by BoomShakaY** [comment]
pair_loss并未使用，相关参数都未用到，请将PAIR_LOSS_WEIGHT设置为0
文中参数是在一块16G V100上取得的，不同机器不同batch_size、以及分布式训练可能会影响其效果，谢谢
